language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo test --verbose --all -- --ignored

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

