[package]
name = "utp"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "1.0.1"
crossbeam-queue = "0.3.1"
futures-core = "0.3.13"
log = "0.4.14"
thiserror = "1.0.24"
tokio = { version = "1.4.0", features = ["net"] }

[dev-dependencies]
futures-util = { version = "0.3.13" }
pretty_env_logger = "0.4.0"
tokio = { version = "1.4.0", features = ["io-util", "macros", "rt-multi-thread"] }
