[package]
name = "utp"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5.6"
crossbeam-deque = "0.7.3"
dashmap = "4.0.0-rc6"
futures-util = "0.3.5"
thiserror = "1.0.20"
tokio = { version = "0.2.22", features = ["dns", "io-util", "macros", "sync", "udp"] }
