[package]
name = "utp"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "1.0.0"
crossbeam-queue = "0.3.1"
futures-util = { version = "0.3.8", features = ["io"] }
log = "0.4.11"
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["net", "sync"] }

[dev-dependencies]
futures-util = "0.3.8"
pretty_env_logger = "0.4.0"
tokio = { version = "1.0.1", features = ["macros", "rt-multi-thread"] }
