[package]
name = "utp"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "1.0.1"
crossbeam-queue = "0.3.2"
dashmap = "4.0.2"
futures-util = "0.3.15"
log = "0.4.14"
thiserror = "1.0.25"
tokio = { version = "1.6.1", features = ["net"] }
rand = "0.8.3"

[dev-dependencies]
futures-util = { version = "0.3.15" }
pretty_env_logger = "0.4.0"
tokio = { version = "1.6.1", features = ["io-util", "macros", "rt-multi-thread"] }
