[package]
name = "utp"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5.6"
crossbeam-queue = "0.2.3"
flume = { version = "0.9.0", default-features = false }
futures-util = "0.3.5"
log = "0.4.11"
thiserror = "1.0.20"
tokio = { version = "0.2.22", features = ["dns", "io-util", "macros", "sync", "udp"] }

[dev-dependencies]
pretty_env_logger = "0.4.0"
tokio = { version = "0.2.22", features = ["dns", "io-util", "macros", "sync", "time", "udp"] }
