[package]
name = "utp"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5.6"
crossbeam-queue = "0.2.3"
log = "0.4.11"
thiserror = "1.0.20"
tokio = { version = "0.2.22", features = ["dns", "sync", "udp"] }

[dev-dependencies]
futures-util = "0.3.5"
pretty_env_logger = "0.4.0"
tokio = { version = "0.2.22", features = ["macros", "rt-threaded"] }
