[package]
name = "utp"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5.5"
num_enum = "0.5.0"
thiserror = "1.0.20"
tokio = { version = "0.2.21", features = ["dns", "io-util", "udp"] }
